# .readthedocs.yml
#
# https://docs.readthedocs.io/en/stable/config-file/v2.html
#
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
  - requirements: docs/requirements.txt

submodules:
  include: all
  recursive: true
