from xchainpy2_utils.consts import NetworkType

BTC_DECIMAL = 8

ROOT_DERIVATION_PATH_44 = "44'/0'/0'/0/"
ROOT_DERIVATION_PATH_49 = "49'/0'/0'/0/"
ROOT_DERIVATION_PATH_84 = "84'/0'/0'/0/"
ROOT_DERIVATION_PATH_TEST_NET_84 = "84'/1'/0'/0/"

ROOT_DERIVATION_PATHS = {
    NetworkType.MAINNET: ROOT_DERIVATION_PATH_84,
    NetworkType.STAGENET: ROOT_DERIVATION_PATH_84,
    NetworkType.TESTNET: ROOT_DERIVATION_PATH_TEST_NET_84,
}

MIN_TX_FEE = 1000

LOWER_FEE_BOUND = 1
UPPER_FEE_BOUND = 1_000
BTC_SYMBOL = '₿'
BTC_SATOSHI_SYMBOL = '⚡'

TX_EMPTY_SIZE = 4 + 1 + 1 + 4
TX_INPUT_BASE = 32 + 4 + 1 + 4
TX_INPUT_PUBKEYHASH = 107
TX_OUTPUT_BASE = 8 + 1
TX_OUTPUT_PUBKEYHASH = 25
