[tool.poetry]
name = "xchainpy_util"
version = "0.1.0"
description = "XCainPy Utils"
authors = ["Tirinox <developer@tirinox.ru>"]
readme = "README.md"
packages = [{include = "xchainpy_util"}]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"