# coding: utf-8

"""
    Thornode API

    Thornode REST API.  # noqa: E501

    OpenAPI spec version: 3.14.1
    Contact: devs@thorchain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Code(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'deployers': 'list[str]',
        'origin': 'str'
    }

    attribute_map = {
        'code': 'code',
        'deployers': 'deployers',
        'origin': 'origin'
    }

    def __init__(self, code=None, deployers=None, origin=None):  # noqa: E501
        """Code - a model defined in Swagger"""  # noqa: E501
        self._code = None
        self._deployers = None
        self._origin = None
        self.discriminator = None
        if code is not None:
            self.code = code
        if deployers is not None:
            self.deployers = deployers
        if origin is not None:
            self.origin = origin

    @property
    def code(self):
        """Gets the code of this Code.  # noqa: E501


        :return: The code of this Code.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this Code.


        :param code: The code of this Code.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def deployers(self):
        """Gets the deployers of this Code.  # noqa: E501


        :return: The deployers of this Code.  # noqa: E501
        :rtype: list[str]
        """
        return self._deployers

    @deployers.setter
    def deployers(self, deployers):
        """Sets the deployers of this Code.


        :param deployers: The deployers of this Code.  # noqa: E501
        :type: list[str]
        """

        self._deployers = deployers

    @property
    def origin(self):
        """Gets the origin of this Code.  # noqa: E501


        :return: The origin of this Code.  # noqa: E501
        :rtype: str
        """
        return self._origin

    @origin.setter
    def origin(self, origin):
        """Sets the origin of this Code.


        :param origin: The origin of this Code.  # noqa: E501
        :type: str
        """

        self._origin = origin

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Code, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Code):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
