# coding: utf-8

"""
    Thornode API

    Thornode REST API.  # noqa: E501

    OpenAPI spec version: 3.4.0
    Contact: devs@thorchain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TradeUnitResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'asset': 'str',
        'units': 'str',
        'depth': 'str'
    }

    attribute_map = {
        'asset': 'asset',
        'units': 'units',
        'depth': 'depth'
    }

    def __init__(self, asset=None, units=None, depth=None):  # noqa: E501
        """TradeUnitResponse - a model defined in Swagger"""  # noqa: E501
        self._asset = None
        self._units = None
        self._depth = None
        self.discriminator = None
        self.asset = asset
        self.units = units
        self.depth = depth

    @property
    def asset(self):
        """Gets the asset of this TradeUnitResponse.  # noqa: E501

        trade account asset with \"~\" separator  # noqa: E501

        :return: The asset of this TradeUnitResponse.  # noqa: E501
        :rtype: str
        """
        return self._asset

    @asset.setter
    def asset(self, asset):
        """Sets the asset of this TradeUnitResponse.

        trade account asset with \"~\" separator  # noqa: E501

        :param asset: The asset of this TradeUnitResponse.  # noqa: E501
        :type: str
        """
        if asset is None:
            raise ValueError("Invalid value for `asset`, must not be `None`")  # noqa: E501

        self._asset = asset

    @property
    def units(self):
        """Gets the units of this TradeUnitResponse.  # noqa: E501

        total units of trade asset  # noqa: E501

        :return: The units of this TradeUnitResponse.  # noqa: E501
        :rtype: str
        """
        return self._units

    @units.setter
    def units(self, units):
        """Sets the units of this TradeUnitResponse.

        total units of trade asset  # noqa: E501

        :param units: The units of this TradeUnitResponse.  # noqa: E501
        :type: str
        """
        if units is None:
            raise ValueError("Invalid value for `units`, must not be `None`")  # noqa: E501

        self._units = units

    @property
    def depth(self):
        """Gets the depth of this TradeUnitResponse.  # noqa: E501

        total depth of trade asset  # noqa: E501

        :return: The depth of this TradeUnitResponse.  # noqa: E501
        :rtype: str
        """
        return self._depth

    @depth.setter
    def depth(self, depth):
        """Sets the depth of this TradeUnitResponse.

        total depth of trade asset  # noqa: E501

        :param depth: The depth of this TradeUnitResponse.  # noqa: E501
        :type: str
        """
        if depth is None:
            raise ValueError("Invalid value for `depth`, must not be `None`")  # noqa: E501

        self._depth = depth

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TradeUnitResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TradeUnitResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
