# coding: utf-8

"""
    Thornode API

    Thornode REST API.  # noqa: E501

    OpenAPI spec version: 3.17.0
    Contact: devs@thorchain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VaultSolvencyAsset(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'asset': 'str',
        'amount': 'str'
    }

    attribute_map = {
        'asset': 'asset',
        'amount': 'amount'
    }

    def __init__(self, asset=None, amount=None):  # noqa: E501
        """VaultSolvencyAsset - a model defined in Swagger"""  # noqa: E501
        self._asset = None
        self._amount = None
        self.discriminator = None
        self.asset = asset
        self.amount = amount

    @property
    def asset(self):
        """Gets the asset of this VaultSolvencyAsset.  # noqa: E501

        Asset identifier  # noqa: E501

        :return: The asset of this VaultSolvencyAsset.  # noqa: E501
        :rtype: str
        """
        return self._asset

    @asset.setter
    def asset(self, asset):
        """Sets the asset of this VaultSolvencyAsset.

        Asset identifier  # noqa: E501

        :param asset: The asset of this VaultSolvencyAsset.  # noqa: E501
        :type: str
        """
        if asset is None:
            raise ValueError("Invalid value for `asset`, must not be `None`")  # noqa: E501

        self._asset = asset

    @property
    def amount(self):
        """Gets the amount of this VaultSolvencyAsset.  # noqa: E501

        Solvency amount for the asset. Positive values indicate over-solvency, negative values indicate under-solvency.  # noqa: E501

        :return: The amount of this VaultSolvencyAsset.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this VaultSolvencyAsset.

        Solvency amount for the asset. Positive values indicate over-solvency, negative values indicate under-solvency.  # noqa: E501

        :param amount: The amount of this VaultSolvencyAsset.  # noqa: E501
        :type: str
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VaultSolvencyAsset, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VaultSolvencyAsset):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
