# Just copy this file, name it tcy_bot_config.yaml

thor:
  node_url: "https://thornode.ninerealms.com/"
  midgard_url: "https://midgard.ninerealms.com/"
  phrase: "your twelve word seed phrase goes here"
  network_id: "mainnet"


strategy:
  source_amount: 100
  source_asset: "THOR.RUNE"
  target_asset: "THOR.TCY"

  check_interval: 1

  min_price_target_per_source_asset: 12.0   # TCY= $0.11 @ 1.32$/Rune

  skip_check: false
