# coding: utf-8

"""
    Thornode API

    Thornode REST API.  # noqa: E501

    OpenAPI spec version: 3.17.0
    Contact: devs@thorchain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xchainpy2_thornode
from xchainpy2_thornode.models.oracle_price import OraclePrice  # noqa: E501
from xchainpy2_thornode.rest import ApiException


class TestOraclePrice(unittest.TestCase):
    """OraclePrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOraclePrice(self):
        """Test OraclePrice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xchainpy2_thornode.models.oracle_price.OraclePrice()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
