# coding: utf-8

"""
    Thornode API

    Thornode REST API.  # noqa: E501

    OpenAPI spec version: 3.17.0
    Contact: devs@thorchain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xchainpy2_thornode
from xchainpy2_thornode.api.swap_api import SwapApi  # noqa: E501
from xchainpy2_thornode.rest import ApiException


class TestSwapApi(unittest.TestCase):
    """SwapApi unit test stubs"""

    def setUp(self):
        self.api = SwapApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_swap_details(self):
        """Test case for swap_details

        """
        pass


if __name__ == '__main__':
    unittest.main()
