# coding: utf-8

"""
    Thornode API

    Thornode REST API.  # noqa: E501

    OpenAPI spec version: 3.17.0
    Contact: devs@thorchain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xchainpy2_thornode
from xchainpy2_thornode.models.swap_state import SwapState  # noqa: E501
from xchainpy2_thornode.rest import ApiException


class TestSwapState(unittest.TestCase):
    """SwapState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSwapState(self):
        """Test SwapState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xchainpy2_thornode.models.swap_state.SwapState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
