# coding: utf-8

"""
    Thornode API

    Thornode REST API.  # noqa: E501

    OpenAPI spec version: 1.108.3
    Contact: devs@thorchain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import thornode_client
from thornode_client.models.outbound_response import OutboundResponse  # noqa: E501
from thornode_client.rest import ApiException


class TestOutboundResponse(unittest.TestCase):
    """OutboundResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutboundResponse(self):
        """Test OutboundResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = thornode_client.models.outbound_response.OutboundResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
