# coding: utf-8

"""
    Thornode API

    Thornode REST API.  # noqa: E501

    OpenAPI spec version: 3.4.0
    Contact: devs@thorchain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xchainpy2_thornode
from xchainpy2_thornode.api.secured_assets_api import SecuredAssetsApi  # noqa: E501
from xchainpy2_thornode.rest import ApiException


class TestSecuredAssetsApi(unittest.TestCase):
    """SecuredAssetsApi unit test stubs"""

    def setUp(self):
        self.api = SecuredAssetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_secured_assets(self):
        """Test case for secured_assets

        """
        pass


if __name__ == '__main__':
    unittest.main()
