# coding: utf-8

"""
    Thornode API

    Thornode REST API.  # noqa: E501

    OpenAPI spec version: 3.4.0
    Contact: devs@thorchain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xchainpy2_thornode
from xchainpy2_thornode.api.secured_asset_api import SecuredAssetApi  # noqa: E501
from xchainpy2_thornode.rest import ApiException


class TestSecuredAssetApi(unittest.TestCase):
    """SecuredAssetApi unit test stubs"""

    def setUp(self):
        self.api = SecuredAssetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_secured_asset(self):
        """Test case for secured_asset

        """
        pass


if __name__ == '__main__':
    unittest.main()
