# coding: utf-8

"""
    Thornode API

    Thornode REST API.  # noqa: E501

    OpenAPI spec version: 2.135.0
    Contact: devs@thorchain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xchainpy2_thornode
from xchainpy2_thornode.api.network_api import NetworkApi  # noqa: E501
from xchainpy2_thornode.rest import ApiException


class TestNetworkApi(unittest.TestCase):
    """NetworkApi unit test stubs"""

    def setUp(self):
        self.api = NetworkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ban(self):
        """Test case for ban

        """
        pass

    def test_constants(self):
        """Test case for constants

        """
        pass

    def test_inbound_addresses(self):
        """Test case for inbound_addresses

        """
        pass

    def test_lastblock(self):
        """Test case for lastblock

        """
        pass

    def test_lastblock_chain(self):
        """Test case for lastblock_chain

        """
        pass

    def test_network(self):
        """Test case for network

        """
        pass

    def test_outbound_fee_asset(self):
        """Test case for outbound_fee_asset

        """
        pass

    def test_outbound_fees(self):
        """Test case for outbound_fees

        """
        pass

    def test_ragnarok(self):
        """Test case for ragnarok

        """
        pass

    def test_version(self):
        """Test case for version

        """
        pass


if __name__ == '__main__':
    unittest.main()
