# coding: utf-8

"""
    Mayanode API

    Mayanode REST API.  # noqa: E501

    OpenAPI spec version: 1.126.0
    Contact: devs@mayachain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xchainpy2_mayanode
from xchainpy2_mayanode.api.trade_units_api import TradeUnitsApi  # noqa: E501
from xchainpy2_mayanode.rest import ApiException


class TestTradeUnitsApi(unittest.TestCase):
    """TradeUnitsApi unit test stubs"""

    def setUp(self):
        self.api = TradeUnitsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_trade_units(self):
        """Test case for trade_units

        """
        pass


if __name__ == '__main__':
    unittest.main()
