# coding: utf-8

"""
    Mayanode API

    Mayanode REST API.  # noqa: E501

    OpenAPI spec version: 1.111.0
    Contact: devs@mayachain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xchainpy2_mayanode
from xchainpy2_mayanode.models.network_response import NetworkResponse  # noqa: E501
from xchainpy2_mayanode.rest import ApiException


class TestNetworkResponse(unittest.TestCase):
    """NetworkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkResponse(self):
        """Test NetworkResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xchainpy2_mayanode.models.network_response.NetworkResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
