# coding: utf-8

"""
    Mayanode API

    Mayanode REST API.  # noqa: E501

    OpenAPI spec version: 1.118.0
    Contact: devs@mayachain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xchainpy2_mayanode
from xchainpy2_mayanode.api.cacao_pool_api import CACAOPoolApi  # noqa: E501
from xchainpy2_mayanode.rest import ApiException


class TestCACAOPoolApi(unittest.TestCase):
    """CACAOPoolApi unit test stubs"""

    def setUp(self):
        self.api = CACAOPoolApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cacao_pool(self):
        """Test case for cacao_pool

        """
        pass

    def test_cacao_provider(self):
        """Test case for cacao_provider

        """
        pass

    def test_cacao_providers(self):
        """Test case for cacao_providers

        """
        pass


if __name__ == '__main__':
    unittest.main()
