# coding: utf-8

"""
    Mayanode API

    Mayanode REST API.  # noqa: E501

    OpenAPI spec version: 1.103.2
    Contact: devs@mayachain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mayanode_client
from mayanode_client.models.buckets_response import BucketsResponse  # noqa: E501
from mayanode_client.rest import ApiException


class TestBucketsResponse(unittest.TestCase):
    """BucketsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBucketsResponse(self):
        """Test BucketsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mayanode_client.models.buckets_response.BucketsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
