# coding: utf-8

"""
    Mayanode API

    Mayanode REST API.  # noqa: E501

    OpenAPI spec version: 1.129.5
    Contact: devs@mayachain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xchainpy2_mayanode
from xchainpy2_mayanode.models.trade_account_response import TradeAccountResponse  # noqa: E501
from xchainpy2_mayanode.rest import ApiException


class TestTradeAccountResponse(unittest.TestCase):
    """TradeAccountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTradeAccountResponse(self):
        """Test TradeAccountResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xchainpy2_mayanode.models.trade_account_response.TradeAccountResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
