# coding: utf-8

"""
    Mayanode API

    Mayanode REST API.  # noqa: E501

    OpenAPI spec version: 1.129.2
    Contact: devs@mayachain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xchainpy2_mayanode
from xchainpy2_mayanode.models.swapper_clout_response import SwapperCloutResponse  # noqa: E501
from xchainpy2_mayanode.rest import ApiException


class TestSwapperCloutResponse(unittest.TestCase):
    """SwapperCloutResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSwapperCloutResponse(self):
        """Test SwapperCloutResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = xchainpy2_mayanode.models.swapper_clout_response.SwapperCloutResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
