# coding: utf-8

"""
    Mayanode API

    Mayanode REST API.  # noqa: E501

    OpenAPI spec version: 1.111.0
    Contact: devs@mayachain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import xchainpy2_mayanode
from xchainpy2_mayanode.api.streaming_swap_api import StreamingSwapApi  # noqa: E501
from xchainpy2_mayanode.rest import ApiException


class TestStreamingSwapApi(unittest.TestCase):
    """StreamingSwapApi unit test stubs"""

    def setUp(self):
        self.api = StreamingSwapApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_stream_swap(self):
        """Test case for stream_swap

        """
        pass

    def test_stream_swaps(self):
        """Test case for stream_swaps

        """
        pass


if __name__ == '__main__':
    unittest.main()
