# coding: utf-8

"""
    Mayanode API

    Mayanode REST API.  # noqa: E501

    OpenAPI spec version: 1.103.2
    Contact: devs@mayachain.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import mayanode_client
from mayanode_client.models.vault_router import VaultRouter  # noqa: E501
from mayanode_client.rest import ApiException


class TestVaultRouter(unittest.TestCase):
    """VaultRouter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVaultRouter(self):
        """Test VaultRouter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mayanode_client.models.vault_router.VaultRouter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
